# Generated by Django 5.2.4 on 2025-07-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_membership_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titile',
            new_name='title',
        ),
    ]
